import type { Metadata } from "next";
import "./globals.css";
import Header from "./(layoutsComp)/Header";
import { CssBaseline, Grid, ThemeProvider } from "@mui/material";
import theme from "@/theme";
import { Roboto } from "next/font/google";
import Footer from "./(layoutsComp)/Footer";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Providers } from "./Providers";
const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  //only download the characters we need for better performance
  subsets: ["latin"],
  //is related to font-display when font is loading, swap is good for performance(prevent Flash of Invisible Text) and very fast Flash of Unstyled Text
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <Providers>
          <AppRouterCacheProvider options={{ key: "css" }}>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <Header />
              <Grid sx={{ minHeight: "100vh" }}>{children}</Grid>
              <Footer />
            </ThemeProvider>
          </AppRouterCacheProvider>
        </Providers>
      </body>
    </html>
  );
}
